### ISSUE TITLE
Compilation error on missing ostream

### ISSUE THREAD

**Issue by rianquinn** [dascandy/hippomocks#60] opened 2016-11-05 14:41 UTC
If an ostream overload doesn't exist for a param type, you get a compilation error on the following code:

```cpp
if (withComma)
    os << ",";
os << arg;
```

I ran into this issue when I had to mock a function that had a `gsl::not_null` param type (from the Guideline Support Library) which doesn't provide an ostream operator. For now I have this commented out..

**Comment by dascandy** [comment] 2016-11-06 22:21
That should've landed you on the "???" printer that is the least specific template I could fabricate. Do you have an idea why that one did not match?

**Comment by rianquinn** [comment] 2016-11-06 23:19
This is the source that is causing it:

https://github.com/rianquinn/hypervisor/blob/vmcall_interface/bfm/test/test_ioctl_driver.cpp#L74

**Comment by dascandy** [comment] 2016-11-11 10:54
This is the code that should handle it: https://github.com/dascandy/hippomocks/blob/master/HippoMocks/hippomocks.h#L436 . 

Minor note: that line shouldn't need [&] as you don't refer to any locals in the lambda. Makes me happy to see that I correctly designed .Do to handle lambdas, when .Do is from 2008 and lambdas were only in C++11 (and GCC since 2012 or so).

Do you have the compile error for me?

**Comment by rianquinn** [comment] 2016-11-11 13:51
Here you go. Thanks a ton for looking into this

```
/home/user/hypervisor/include/hippomocks.h: In instantiation of ‘static void printArg<T>::print(std::ostream&, T, bool) [with T = gsl::not_null<debug_ring_resources_t*>; std::ostream = std::basic_ostream<char>]’:
/home/user/hypervisor/include/hippomocks.h:612:22:   required from ‘void ref_tuple<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>::printTo(std::ostream&) const [with A = gsl::not_null<debug_ring_resources_t*>; B = long unsigned int; C = NullType; D = NullType; E = NullType; F = NullType; G = NullType; H = NullType; I = NullType; J = NullType; K = NullType; L = NullType; M = NullType; N = NullType; O = NullType; P = NullType; std::ostream = std::basic_ostream<char>]’
/home/user/hypervisor/bfm/test/test_ioctl_driver.cpp:1919:1:   required from here
/home/user/hypervisor/include/hippomocks.h:464:6: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘gsl::not_null<debug_ring_resources_t*>’)
   os << arg;
      ^
In file included from /usr/include/c++/5/iostream:39:0,
                 from /home/user/hypervisor/include/gsl/gsl_util:32,
                 from /home/user/hypervisor/include/gsl/gsl:36,
                 from /home/user/hypervisor/include/unittest.h:29,
                 from /home/user/hypervisor/bfm/test/./test.h:25,
                 from /home/user/hypervisor/bfm/test/test_ioctl_driver.cpp:22:
/usr/include/c++/5/ostream:174:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(bool) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(bool __n)
       ^
/usr/include/c++/5/ostream:245:7: note: candidate: std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(const void*) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]
       operator<<(const void* __p)
       ^
In file included from /home/user/hypervisor/include/unittest.h:41:0,
                 from /home/user/hypervisor/bfm/test/./test.h:25,
                 from /home/user/hypervisor/bfm/test/test_ioctl_driver.cpp:22:
/home/user/hypervisor/include/hippomocks.h:439:22: note: candidate: std::ostream& operator<<(std::ostream&, const NotPrintable&)
 inline std::ostream &operator<<(std::ostream &os, NotPrintable const&)
                      ^
```

**Comment by rianquinn** [comment] 2016-11-11 13:52
my compiler is GCC 5.X

**Comment by dascandy** [comment] 2016-11-11 13:57
... Oh, it's confused which one is the better match. Well, given that there's two ways to print your type already your problem shouldn't be that this adds a third to the overload set. Perhaps it's a better idea to explain to ostream how to print a gsl::not_null ? I would have hoped the GSL itself contains this...

**Comment by rianquinn** [comment] 2016-11-11 14:02
I'd be surprised if I had any luck trying to upstream an ostream overload. I can try if needed.

**Comment by dascandy** [comment] 2016-11-11 14:07
Right now not_null is a pointer wrapper that makes it unprintable, and you can work around it by overloading it literally everywhere. Perhaps changing it to convert to bool only explicitly would be better?

**Comment by rianquinn** [comment] 2016-11-11 14:14
That makes sense to me.

**Comment by dascandy** [comment] 2016-11-11 14:15
Thing is, if they either make the operator bool explicit or hide it, *then* this bug is on me because then this is the only other overload.

**Comment by rianquinn** [comment] 2016-11-11 14:17
Ok, before we go any further let me see if an ostream overload is something they are interested in

**Comment by dascandy** [comment] 2016-11-25 20:39
Marking this as a duplicate of #23, please feel free to discuss further in there. When GSL adds an ostream overload your problem is gone, but if they disambiguate these two it's #23.

**Closed by dascandy** 2016-11-25 20:39 UTC
