### ISSUE TITLE
Compilation error MSVC 2015

### ISSUE THREAD

**Issue by farnyser** [dascandy/hippomocks#55] opened 2016-07-27 16:49 UTC
Hello,

I'm trying to use HipoMocks but it seems to be broken on VS2015 

``` cpp
class ID {
public:
    virtual ~ID() {};
    virtual int f();
    virtual std::string g() = 0;
};

BOOST_AUTO_TEST_CASE(MyTest)
{
    MockRepository mocks;
    ID *iamock = mocks.Mock<ID>();
    mocks.ExpectCall(iamock, ID::f).Return(1);
    mocks.ExpectCall(iamock, ID::g).Return("fsck");
    BOOST_CHECK(iamock->f() == 1);
    BOOST_CHECK(iamock->g() == "fsck");
}
```

Error message:

```
hippomocks.h(1245): error C4700: uninitialized local variable 'conv' used
```

This is the code:

``` cpp
    if (value != -1)
        return std::pair<int, int>((int)(conv.u.baseoffs/sizeof(void*)), value);
```

**Comment by dascandy** [comment] 2016-07-28 06:10
That's surprising, since as far as I know conv is a union specifically to do this kind of conversion. Let me check tonight when I have access to a Windows machine again.

**Comment by dascandy** [comment] 2016-11-25 20:08
Found the cause. Should be fixed now; can you check on the cpp11 branch?

**Closed** 2016-11-25 20:38 UTC
